import StyledComponentsRegistry from "../lib/registry";
import Footer from "./components/footer/Footer";
import Navigator from "./components/nav/Navigator";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body>
        <Navigator />
        <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
        <Footer />
      </body>
    </html>
  );
}
